# Generated by Django 5.0.3 on 2024-03-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='baccarat_app',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='chat_app',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='cricket_app',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='earning_app',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='slot_app',
        ),
    ]
